# Generated by Django 4.0.1 on 2022-01-24 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('weight', models.PositiveSmallIntegerField()),
                ('equipment_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.equipmentcategory')),
                ('gear_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='firstapp.gearcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('quantity', models.PositiveSmallIntegerField()),
                ('cost_unit_type', models.CharField(max_length=5)),
                ('equipment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='firstapp.equipment')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.usercollection')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.equipment')),
            ],
        ),
    ]
