# Generated by Django 4.0.1 on 2022-01-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_damagetype_weapontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='damage',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
