# Generated by Django 4.0.1 on 2022-02-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_weapon_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='properties',
            field=models.ManyToManyField(to='items.WeaponProperty'),
        ),
        migrations.DeleteModel(
            name='WeaponWeaponProperty',
        ),
    ]
